params:
    fastp:
      min_len: 60 # Recommended value >= 50.
      n_base_limit: 0 # Recommended value 0.
      adapter_r1: "" # adapter for read1. If not specified, the adapter will be auto-detected.
      adapter_r2: "" # adapter for read2. If not specified, the adapter will be auto-detected.
    align:
      threads: 8 # BWA mem threads.
    ref_num: 5 # Number of reference genomes with the highest mapping rate needs to be output

assay:
    trimming: "1.assay/01.trimming"
    align: "1.assay/02.align"
    filter: "1.assay/03.filter"

results:
    "2.result"

logs:
    trimming: "1.assay/logs/01.trimming"
    align: "1.assay/logs/02.align"
